=== Kan-86/XML-JSONValidationAndQueries/BooksAndUsersXMLJSON/LibraryDTD.dtd
<!ELEMENT Library (User+)>

<!ELEMENT User (Name,Address,BooksRented+)>
<!ATTLIST User Id ID #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT BooksRented (Title,Author,Genre)>
<!ATTLIST BooksRented Id ID #REQUIRED>
<!ATTLIST BooksRented UserId IDREF #REQUIRED>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Genre (#PCDATA)>

=== Kan-86/XML-JSONValidationAndQueries/BooksAndUsersXMLJSON/BooksXML.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE Library SYSTEM "LibraryDTD.dtd">
<Library>
  <User>
    <Name></Name>
    <Address></Address>
    <BooksRented>
      <Title></Title>
      <Author></Author>
      <Genre></Genre>
    </BooksRented>
  </User>
</Library>
